/**
 * File: ui.js
 * Description: Contains functions responsible for manipulating the DOM, such as displaying results, updating progress bars, managing modals, etc.
 * Author: D.A.R.Y.L. & Taylor Giddens
 */

// --- UI Functions ---
// This file contains functions responsible for manipulating the DOM,
// such as displaying results, updating progress bars, managing modals, etc.

/**
 * Handles drag over events for the file drop zone.
 */
function handleFileDragOver(event) {
    event.preventDefault();
    dropZoneContainer.classList.add('drag-over');
}

/**
 * Handles drag leave events for the file drop zone.
 */
function handleFileDragLeave(event) {
    event.preventDefault();
    dropZoneContainer.classList.remove('drag-over');
}

/**
 * Handles file drop events for the file drop zone.
 */
function handleFileDrop(event) {
    event.preventDefault(); // FIX: Prevent the browser from opening the file
    dropZoneContainer.classList.remove('drag-over');

    const files = event.dataTransfer.files;
    if (files.length) {
        // Set the file list on the hidden input and manually trigger change event
        fileUploadInput.files = files;
        fileUploadInput.dispatchEvent(new Event('change', { bubbles: true }));
    }
}


/**
 * Handles the file upload, parsing it with SheetJS or JSON.
 */
function handleFileUpload(event) {
    const file = event.target.files[0];
    if (!file) return;

    fileNameDisplay.textContent = file.name;
    ticketCountDisplay.classList.add('hidden');
    analysisSection.classList.add('hidden');
    resultsSection.classList.add('hidden');
    statsSection.classList.add('hidden');
    if (tokenCountWarning) tokenCountWarning.classList.add('hidden'); // Defensive check

    // Determine the expected file type based on the extraction profile
    const extractionProfile = extractionProfileSelect.value;
    const isUploadExtract = extractionProfile === 'upload-extract';
    const isJson = file.name.toLowerCase().endsWith('.json');

    // Validation based on extraction profile
    if (isUploadExtract && !isJson) {
        displayError('For "Upload Extract" mode, please upload a JSON file previously generated by D.A.R.Y.L.');
        fileUploadInput.value = '';
        fileNameDisplay.textContent = '';
        return;
    } else if (!isUploadExtract && isJson) {
        // Allow JSON upload, but user needs to manually select column
        console.warn('JSON file uploaded in FreshService mode. Assuming data requires column selection.');
    }


    const reader = new FileReader();
    reader.onload = (e) => {
        try {
            if (isJson || isUploadExtract) {
                // Handle JSON files
                const rawData = JSON.parse(e.target.result);
                // The JSON generated by D.A.R.Y.L. is an array of ticket objects
                if (Array.isArray(rawData)) {
                    sheetData = rawData;
                    // For JSON, there is no column selection needed if we are just counting/analyzing the array itself.

                    if (isUploadExtract) {
                        // No column needed for JSON extract, allFetchedData is the array.
                        updateTicketCount(true, 'JSON Extract');
                    } else {
                        // Infer column headers from the first object's keys, treating it like a flattened structure (though it's complex)
                        const headers = getJsonHeaders(rawData);
                        columnSelect.innerHTML = '<option value="">Select column with Ticket IDs</option>';
                        headers.forEach(header => {
                            const option = document.createElement('option');
                            option.value = header;
                            option.textContent = header;
                            columnSelect.appendChild(option);
                        });
                        columnSelect.disabled = false;

                        const keywords = ['ticketid', 'id', 'ticket.id'];
                        const foundHeader = headers.find(h => keywords.some(k => h.toLowerCase().includes(k)));

                        if (foundHeader) {
                            columnSelect.value = foundHeader;
                            updateTicketCount(true, foundHeader);
                        } else {
                            updateTicketCount(false);
                        }
                    }

                } else {
                    throw new Error("JSON file format is invalid. Expected an array of ticket objects.");
                }

            } else {
                // Handle Excel/CSV files (via SheetJS)
                const data = new Uint8Array(e.target.result);
                const workbook = XLSX.read(data, {
                    type: 'array'
                });
                const firstSheetName = workbook.SheetNames[0];
                const worksheet = workbook.Sheets[firstSheetName];
                sheetData = XLSX.utils.sheet_to_json(worksheet);

                if (sheetData.length > 0) {
                    const headers = Object.keys(sheetData[0]);
                    columnSelect.innerHTML = '<option value="">Select column with Ticket IDs</option>';
                    headers.forEach(header => {
                        const option = document.createElement('option');
                        option.value = header;
                        option.textContent = header;
                        columnSelect.appendChild(option);
                    });
                    columnSelect.disabled = false;
                    displayError('', false); // Clear non-fatal errors

                    const keywords = ['ticket', 'request', 'problem', 'incident', 'id'];
                    const foundHeader = headers.find(h => keywords.some(k => h.toLowerCase().includes(k)));

                    if (foundHeader) {
                        columnSelect.value = foundHeader;
                        updateTicketCount(true, foundHeader);
                    } else {
                        updateTicketCount(false);
                    }
                } else {
                    displayError('The uploaded file is empty or could not be read.');
                    columnSelect.disabled = true;
                }
            }
        } catch (error) {
            displayError(`Error reading the file (${file.name}). Please ensure it is a valid, uncorrupted file in the correct format.`);
            console.error("File read error:", error);
            sheetData = [];
            columnSelect.disabled = true;
        }
    };

    // Read JSON as text, or Excel/CSV as array buffer
    if (isJson || isUploadExtract) {
        reader.readAsText(file);
    } else {
        reader.readAsArrayBuffer(file);
    }
}

/**
 * Helper to flatten JSON structure for column selection headers.
 */
function getJsonHeaders(dataArray) {
    if (!dataArray || dataArray.length === 0) return [];

    const headers = new Set();
    const traverse = (obj, prefix = '') => {
        for (const key in obj) {
            if (obj.hasOwnProperty(key)) {
                const currentKey = prefix ? `${prefix}.${key}` : key;
                if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
                    traverse(obj[key], currentKey);
                } else if (Array.isArray(obj[key])) {
                    // For arrays, we don't dive in, just list the field itself (e.g., 'conversations', 'tags')
                    headers.add(currentKey);
                } else {
                    headers.add(currentKey);
                }
            }
        }
    };

    // Only process the first item for header inference
    if (dataArray[0] && dataArray[0].ticket) {
        // If it looks like a DARYL-generated extract (top level ticket/conversations)
        traverse(dataArray[0]);
        // Also add the top-level analysis fields that might exist
        ['problem_summary', 'product_module', 'use_case', 'ticket_id', 'department_id', 'company_name'].forEach(h => headers.add(h));
    } else {
        // Assume simple flat array if not detected as DARYL extract
        traverse(dataArray[0]);
    }

    return Array.from(headers).sort();
}

/**
 * Updates the UI with the number of tickets found.
 */
function updateTicketCount(wasAutoSelected = null, header = '') {
    const selectedProfile = extractionProfileSelect.value;
    const isUploadExtract = selectedProfile === 'upload-extract';
    let message = '';
    let details = '';
    let ticketIds = [];
    if (tokenCountWarning) tokenCountWarning.classList.add('hidden'); // Defensive check

    // Rule 5: Show/hide column selector
    columnSelectContainer.classList.toggle('hidden', isUploadExtract || sheetData.length === 0);

    if (sheetData.length > 0) {
        if (isUploadExtract) {
            // JSON Extract Mode
            ticketIds = sheetData.map(t => t.ticket ? (t.ticket.id || 'N/A') : 'N/A').filter(id => id && id !== 'N/A');
            message = `Found ${ticketIds.length} ticket records in the uploaded JSON Extract.`;
            details = 'Ready for immediate AI analysis.';
            columnSelect.disabled = true;
            columnSelectContainer.classList.add('hidden');

        } else {
            // Light/Extended Mode
            const selectedColumn = columnSelect.value;
            if (selectedColumn) {
                ticketIds = sheetData.map(row => {
                    const value = getDeepValue(row, selectedColumn) || '';
                    return String(value).replace(/\D/g, '');
                }).filter(id => id && id.trim() !== '');

                message = `Found ${ticketIds.length} FreshService Ticket IDs.`;

                if (wasAutoSelected) {
                    details = `Automatically selected column "${header}". You can change this if incorrect.`;
                } else {
                    details = `IDs will be extracted from column "${selectedColumn}" for fetching.`;
                }
            } else if (wasAutoSelected === false) {
                message = `Could not automatically identify the Ticket ID column.`;
                details = `Please select the correct column manually to proceed with fetching.`;
            } else {
                // No file uploaded or column selected yet
                ticketCountDisplay.classList.add('hidden');
                analysisSection.classList.add('hidden');
                return;
            }
            columnSelect.disabled = false;
            columnSelectContainer.classList.remove('hidden');
        }
    } else {
        ticketCountDisplay.classList.add('hidden');
        analysisSection.classList.add('hidden');
        // Ensure prompt 2 is hidden if no file
        prompt2Section.classList.add('hidden');
        return;
    }

    if (message) {
        const baseClass = isUploadExtract ? 'border-green-600 bg-green-50' : 'border-blue-600 bg-blue-50';
        ticketCountDisplay.className = `border-l-4 ${baseClass} p-4 rounded-r-lg`;
        ticketCountDisplay.classList.remove('hidden');

        ticketCountText.textContent = message;
        ticketCountDetails.textContent = details;
        ticketCountDetails.classList.toggle('hidden', !details);
    } else {
        ticketCountDisplay.classList.add('hidden');
    }

    // --- NEW: Handle Chunked Analysis UI Logic ---
    const jobType = document.querySelector('input[name="jobType"]:checked').value;
    if (jobType === 'chunked' && ticketIds.length > 20) {
        prompt2Section.classList.remove('hidden');
    } else {
        prompt2Section.classList.add('hidden');
    }

    if (ticketIds.length > 0) {
        analysisSection.classList.remove('hidden');
        inProgressControls.classList.remove('hidden');
        startButton.classList.remove('hidden');
        // Ensure pause/cancel are hidden when setting up a new run
        pauseButton.classList.add('hidden');
        cancelButton.classList.add('hidden');
        scrollToElement(analysisSection);
    } else {
        analysisSection.classList.add('hidden');
    }
}

/**
 * Helper function to get deep nested value from an object using a dot-notated path.
 */
function getDeepValue(obj, path) {
    if (!obj || !path) return undefined;
    const parts = path.split('.');
    let current = obj;
    for (const part of parts) {
        if (current === null || typeof current !== 'object' || Array.isArray(current)) {
            return undefined;
        }
        current = current[part];
    }
    return current;
}


/**
 * Clears the selected prompt and hides the description.
 */
function handleClearPromptSelection(shouldUpdateCount = true) {
    promptSelectInput.value = '';
    promptDescriptionContainer.classList.add('hidden');
    promptDescriptionText.textContent = '';
    currentPrompt = null;
    clearPromptSelectionBtn.classList.add('hidden');
    if (shouldUpdateCount) {
        updateTicketCount();
        saveSettings();
    }
}

/**
 * Handles the selection of a second prompt (for Chunked mode).
 */
function handlePrompt2Selection() {
    const selectedPromptName = prompt2SelectInput.value;
    const selectedPrompt = allPrompts.find(p => p.name === selectedPromptName);

    if (selectedPrompt) {
        currentPrompt2 = selectedPrompt;
        prompt2DescriptionText.textContent = selectedPrompt.description;
        prompt2DescriptionContainer.classList.remove('hidden');
        clearPrompt2SelectionBtn.classList.remove('hidden');
    } else {
        currentPrompt2 = null;
        prompt2DescriptionContainer.classList.add('hidden');
        prompt2DescriptionText.textContent = '';
        clearPrompt2SelectionBtn.classList.add('hidden');
    }
}

/**
 * Clears the selected prompt 2.
 */
function handleClearPrompt2Selection() {
    prompt2SelectInput.value = '';
    prompt2DescriptionContainer.classList.add('hidden');
    prompt2DescriptionText.textContent = '';
    currentPrompt2 = null;
    clearPrompt2SelectionBtn.classList.add('hidden');
}


/**
 * Creates and displays specific download buttons for the Chunked Analysis workflow.
 */
function displayChunkedDownloads(chunkResults, markdownReport, analysisSucceeded = true) {
    downloadContainer.innerHTML = '';

    // 1. Button to download all intermediate chunk JSONs
    if (chunkResults && chunkResults.length > 0) {
        const intermediateBtn = document.createElement('button');
        intermediateBtn.className = "inline-block bg-teal-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 mr-2 mb-2";
        intermediateBtn.textContent = "Download Intermediate Results (JSON)";
        intermediateBtn.addEventListener('click', () => {
            // Download as a single JSON array of result objects
            const dataStr = JSON.stringify(chunkResults, null, 2);
            const blob = new Blob([dataStr], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = "chunked_analysis_intermediate.json";
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        });
        downloadContainer.appendChild(intermediateBtn);
    }

    // 2. Standard Report Download Buttons (Copy, PDF, CSVs extracted from report)
    if (markdownReport && analysisSucceeded) {
        // Copy Report Button (RAW HTML)
        const copyButton = document.createElement('button');
        copyButton.className = "inline-block bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2 mb-2";
        copyButton.textContent = "Copy Report (Raw HTML)";
        copyButton.addEventListener('click', () => {
            const reportElement = resultsContainer.querySelector('.prose') || resultsContainer.querySelector('iframe')?.contentDocument?.body;
            if (!reportElement) return;

            // NEW: Copy raw HTML code instead of rendered text
            const rawHtml = reportElement.innerHTML;
            const tempTextArea = document.createElement('textarea');
            tempTextArea.value = rawHtml;
            document.body.appendChild(tempTextArea);
            tempTextArea.select();

            try {
                const successful = document.execCommand('copy');
                if (successful) {
                    const originalText = copyButton.textContent;
                    copyButton.textContent = "Copied!";
                    copyButton.classList.add('bg-green-500', 'hover:bg-green-600');
                    copyButton.classList.remove('bg-indigo-600', 'hover:bg-indigo-700');
                    setTimeout(() => {
                        copyButton.textContent = originalText;
                        copyButton.classList.remove('bg-green-500', 'hover:bg-green-600');
                        copyButton.classList.add('bg-indigo-600', 'hover:bg-indigo-700');
                    }, 2000);
                }
            } catch (err) {
                console.error('Failed to copy text.', err);
            }
            document.body.removeChild(tempTextArea);
        });
        downloadContainer.appendChild(copyButton);

        // Download PDF Button
        const downloadPdfButton = document.createElement('button');
        downloadPdfButton.className = "inline-block bg-blue-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 mr-2 mb-2";
        downloadPdfButton.textContent = "Download Report (PDF)";
        downloadPdfButton.addEventListener('click', () => {
            // Reusing existing PDF logic
            let reportElement = resultsContainer.querySelector('.prose');
            if (!reportElement && resultsContainer.querySelector('iframe')) {
                reportElement = resultsContainer.querySelector('iframe').contentDocument.body;
            }

            const headerElement = document.getElementById('pageHeader');
            if (reportElement && typeof window.html2canvas !== 'undefined' && typeof window.jspdf !== 'undefined') {
                const originalFont = reportElement.style.fontFamily;
                reportElement.style.fontFamily = "'Helvetica', 'Arial', sans-serif";
                headerElement.style.display = 'none';
                requestAnimationFrame(() => {
                    setTimeout(() => {
                        html2canvas(reportElement, { scale: 2, useCORS: true, windowWidth: reportElement.scrollWidth, windowHeight: reportElement.scrollHeight }).then(canvas => {
                            reportElement.style.fontFamily = originalFont;
                            headerElement.style.display = 'flex';
                            const { jsPDF } = window.jspdf;
                            const pdf = new jsPDF('p', 'mm', 'a4');
                            const imgData = canvas.toDataURL('image/png');
                            const pdfWidth = pdf.internal.pageSize.getWidth();
                            const pdfHeight = pdf.internal.pageSize.getHeight();
                            const imgProps = pdf.getImageProperties(imgData);
                            const pdfImageHeight = (imgProps.height * pdfWidth) / imgProps.width;

                            // Simple multipage logic
                            let heightLeft = pdfImageHeight;
                            let position = 0;

                            pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfImageHeight);
                            heightLeft -= pdfHeight;

                            while (heightLeft >= 0) {
                                position = heightLeft - pdfImageHeight;
                                pdf.addPage();
                                pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfImageHeight);
                                heightLeft -= pdfHeight;
                            }

                            pdf.save('DARYL-Chunked-Report.pdf');
                        });
                    }, 100);
                });
            }
        });
        downloadContainer.appendChild(downloadPdfButton);

        // Extract CSVs from the report if any are embedded in code blocks
        const { csvs } = parseOverallReport(markdownReport); // Reuse parser to find CSV blocks
        csvs.forEach(csv => {
            const button = document.createElement('button');
            button.className = "inline-block bg-green-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 mr-2 mb-2";
            button.textContent = `Download ${csv.filename}`;
            button.addEventListener('click', () => {
                const blob = new Blob([csv.content], { type: 'text/csv;charset=utf-8;' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = csv.filename;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            });
            downloadContainer.appendChild(button);
        });
    }

    // Always add the raw retrieved data JSON download button
    const jsonButton = document.createElement('button');
    jsonButton.className = "inline-block bg-teal-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 mb-2";
    jsonButton.textContent = "Download Raw Source Data (JSON)";
    jsonButton.addEventListener('click', handleDownload); // Uses global handleDownload
    downloadContainer.appendChild(jsonButton);

    downloadContainer.classList.remove('hidden');
}


/**
 * Creates the color-coded severity pill HTML.
 */
function getPriorityPill(priority) {
    const priorities = {
        1: { text: 'Low', color: 'bg-green-600' },
        2: { text: 'Medium', color: 'bg-yellow-500' },
        3: { text: 'High', color: 'bg-orange-500' },
        4: { text: 'Urgent', color: 'bg-red-600' }
    };
    const { text, color } = priorities[priority] || { text: 'Unknown', color: 'bg-slate-400' };
    return `<p class="px-3 py-1 text-xs font-bold text-white ${color} rounded-full">${text}</p>`;
}

/**
 * Translates a status number to a human-readable string.
 */
function getStatusText(status) {
    const statuses = { 2: "Open", 3: "Pending", 4: "Resolved", 5: "Closed" };
    return statuses[status] || 'Unknown';
}

/**
 * Generates the inner HTML for a result card.
 * @param {object} data The combined analysis and ticket data.
 * @param {string} fsDomain The FreshService domain for link construction.
 * @returns {string} The HTML string for the card's content.
 */
function generateCardHTML(data, fsDomain) {
    const isFsFetch = extractionProfileSelect.value !== 'upload-extract';
    let deepAnalysisPillHtml = '';

    // Check the cache to see if deep analysis has been completed.
    if (extendedAnalysisCache[data.ticket_id]) {
        const checkmarkSVG = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" class="inline-block ml-1.5 -mr-0.5"><circle cx="12" cy="12" r="11" fill="#22c55e" stroke="#fff" stroke-width="1.5"></circle><path d="M8 12.5l3 3 5-6" stroke="white" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"></path></svg>`;
        deepAnalysisPillHtml = `<p class="flex items-center px-3 py-1 text-xs font-bold text-white bg-blue-600 rounded-full">Deep Analysis ${checkmarkSVG}</p>`;
    }

    if (data.error) {
        return `
            <div class="flex justify-between items-center">
                <p class="font-bold text-slate-800">Ticket #${data.ticket_id || data.ticketId}</p>
                <p class="px-2 py-1 text-xs font-semibold text-red-800 bg-red-100 rounded-full">Error</p>
            </div>
            <p class="mt-2 text-sm text-red-600">${data.error}</p>
        `;
    } else {
        const domain = fsDomain.trim().replace(/^https?:\/\//, '');

        // Only show a link if we fetched from FreshService AND a domain is available
        const linkHtml = (domain && isFsFetch) ?
            `<a href="https://${domain}/a/tickets/${data.ticket_id}" target="_blank" class="font-bold text-slate-800 hover:text-indigo-600 hover:underline" onclick="event.stopPropagation()">Ticket #${data.ticket_id}</a>` :
            `<p class="font-bold text-slate-800">Ticket #${data.ticket_id}</p>`;

        // Log link suppression if applicable
        if (!domain || !isFsFetch) {
            console.warn(`Link to FreshService ticket Ticket #${data.ticket_id} suppressed because FreshService domain is not configured or data was uploaded.`);
        }

        return `
            <div class="flex justify-between items-center">
                ${linkHtml}
                <div class="flex items-center space-x-2">
                    ${deepAnalysisPillHtml}
                    ${getPriorityPill(data.priority)}
                </div>
            </div>
            <div class="mt-4 grid grid-cols-[max-content,1fr] gap-y-2 text-sm">
                <div class="font-semibold text-slate-600 text-right pr-2.5">Company Name:</div>
                <div class="text-slate-900 pl-2.5">${data.company_name || 'N/A'}</div>

                <div class="font-semibold text-slate-600 text-right pr-2.5">Problem Summary:</div>
                <div class="text-slate-900 pl-2.5">${data.problem_summary || 'N/A'}</div>
                
                <div class="font-semibold text-slate-600 text-right pr-2.5">Use-Case:</div>
                <div class="text-slate-900 pl-2.5">${data.use_case || 'N/A'}</div>

                <div class="font-semibold text-slate-600 text-right pr-2.5">Product Module:</div>
                <div class="text-slate-900 pl-2.5">${data.product_module || 'N/A'}</div>

                <div class="font-semibold text-slate-600 text-right pr-2.5">Ticket Type:</div>
                <div class="text-slate-900 pl-2.5">${data.type || 'N/A'}</div>

                <div class="font-semibold text-slate-600 text-right pr-2.5">Ticket Status:</div>
                <div class="text-slate-900 pl-2.5">${getStatusText(data.status)}</div>
            </div>
        `;
    }
}


/**
 * Displays a single per-ticket analysis result as a card.
 * @param {object} data The combined analysis and ticket data.
 * @param {object} rawData The raw ticket data object.
 * @param {string} fsDomain The FreshService domain for link construction.
 */
function displayResult(data, rawData, fsDomain) {
    const card = document.createElement('div');
    card.className = 'status-card bg-white p-4 rounded-lg shadow-sm border border-slate-200 cursor-pointer hover:shadow-md hover:border-indigo-300 transition-all';
    card.dataset.ticketId = data.ticket_id;

    // Pass the domain to card HTML generation
    card.innerHTML = generateCardHTML(data, fsDomain);

    card.addEventListener('dblclick', () => {
        showExtendedDetailsModal(data, rawData, fsDomain); // Pass domain to modal
    });


    resultsContainer.appendChild(card);
    setTimeout(() => card.classList.add('visible'), 10);
}


/**
 * Parses the full Gemini response to separate the Markdown report from CSV data.
 */
function parseOverallReport(reportText) {
    const csvs = [];
    let fullText = reportText;

    // specialized check: If the report is an HTML document wrapped in markdown code fences, extract it.
    const htmlBlockRegex = /```html\s*([\s\S]*?)```/i;
    const htmlMatch = fullText.match(htmlBlockRegex);
    if (htmlMatch) {
        const potentialHtml = htmlMatch[1].trim();
        // Verify it looks like a full HTML document
        if (/^\s*<!DOCTYPE html>/i.test(potentialHtml) || /^\s*<html/i.test(potentialHtml)) {
            return {
                markdownReport: potentialHtml,
                csvs: [] // HTML reports typically don't have the CSV sections appended in this tool's context
            };
        }
    }

    // Find the start of the actual markdown report, ignoring any preamble.
    const reportStartMatch = fullText.match(/^#+\s/m);
    if (reportStartMatch) {
        fullText = fullText.substring(reportStartMatch.index);
    }

    // Clean up markdown code fences (Robust Regex Version)
    let cleanText = fullText.trim();

    // Removes start fence like ```html, ```markdown, or just ```. Handles optional preamble if it wasn't caught above.
    cleanText = cleanText.replace(/^[\s\S]*?```[a-zA-Z]*\n/, '');

    // Removes end fence ```
    cleanText = cleanText.replace(/```$/, '').trim();

    let markdownReport = cleanText;

    const csvMarkers = [
        "A. Summary Data (ticket_summary.csv)",
        "B. Tickets for Further Exploration (further_exploration_tickets.csv)"
    ];

    let firstCsvIndex = -1;

    // Find the earliest position of a CSV marker in the report
    for (const marker of csvMarkers) {
        // Use a regex to find the marker, ignoring leading markdown heading characters and whitespace
        const regex = new RegExp(`^#*\\s*${marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
        const match = markdownReport.match(regex);
        if (match) {
            const index = match.index;
            if (firstCsvIndex === -1 || index < firstCsvIndex) {
                firstCsvIndex = index;
            }
        }
    }

    if (firstCsvIndex !== -1) {
        const reportOnlyText = markdownReport.substring(0, firstCsvIndex).trim();
        let remainingText = markdownReport.substring(firstCsvIndex);

        // Process each CSV section
        csvMarkers.forEach((marker, i) => {
            const nextMarker = csvMarkers[i + 1];
            const startRegex = new RegExp(`^#*\\s*${marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
            const startMatch = remainingText.match(startRegex);

            if (startMatch) {
                let content = remainingText.substring(startMatch.index + startMatch[0].length);

                if (nextMarker) {
                    const endRegex = new RegExp(`^#*\\s*${nextMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
                    const endMatch = content.match(endRegex);
                    if (endMatch) {
                        content = content.substring(0, endMatch.index);
                    }
                }

                const filename = marker.substring(marker.indexOf('(') + 1, marker.indexOf(')'));
                content = content.replace(/^Code snippet\s*/, '').trim();
                if (content.startsWith('```') && content.endsWith('```')) {
                    content = content.substring(content.indexOf('\n') + 1, content.lastIndexOf('```')).trim();
                } else if (content.startsWith('```')) {
                    content = content.substring(content.indexOf('\n') + 1).trim();
                }

                csvs.push({
                    filename,
                    content: content.trim()
                });
            }
        });

        markdownReport = reportOnlyText;
    }

    return {
        markdownReport,
        csvs
    };
}


/**
 * Renders the overall analysis report. Detects HTML vs Markdown.
 */
function displayOverallReport(reportContent) {
    resultsContainer.innerHTML = '';

    // Detect if the content is a full HTML document
    const isHtml = /^\s*<!DOCTYPE html>/i.test(reportContent) || /^\s*<html/i.test(reportContent);

    if (isHtml) {
        // Create an iframe to render the HTML report correctly (isolates CSS and allows Scripts)
        const iframe = document.createElement('iframe');
        iframe.style.width = '100%';
        iframe.style.height = '100vh'; // Full height
        iframe.style.border = 'none';
        iframe.className = 'bg-white rounded-lg shadow-sm border border-slate-200';

        resultsContainer.appendChild(iframe);

        // Write the HTML content into the iframe
        const doc = iframe.contentWindow.document;
        doc.open();
        doc.write(reportContent);
        doc.close();

    } else {
        // Fallback to existing Markdown rendering logic
        const reportContainer = document.createElement('div');
        reportContainer.className = 'prose max-w-none p-6 bg-white rounded-lg shadow-sm border border-slate-200';

        if (typeof marked !== 'undefined') {
            const renderer = new marked.Renderer();
            renderer.link = function (href, title, text) {
                try {
                    const fsDomain = fsDomainInput.value.trim().replace(/^https?:\/\//, '');
                    const isFsFetch = extractionProfileSelect.value !== 'upload-extract';
                    const isTicketLink = href.includes(fsDomain) && href.includes('/a/tickets/');

                    if (isTicketLink && (!fsDomain || !isFsFetch)) {
                        return text;
                    }
                    new URL(href);
                    const link = marked.Renderer.prototype.link.call(this, href, title, text);
                    return link.replace(/^<a /, '<a target="_blank" rel="noopener noreferrer" ');
                } catch (e) {
                    return text;
                }
            };

            reportContainer.innerHTML = marked.parse(reportContent, {
                mangle: false,
                headerIds: false,
                renderer: renderer
            });
        } else {
            const pre = document.createElement('pre');
            pre.className = 'whitespace-pre-wrap font-mono text-sm';
            pre.textContent = reportContent;
            reportContainer.appendChild(pre);
        }
        resultsContainer.appendChild(reportContainer);
    }

    if (reportContent.includes('## Analysis Failed')) {
        playNotificationSound('error');
        showOsNotification('Analysis Failed', 'An error occurred during the overall analysis.');
    }
}


/**
 * Creates and displays download buttons for the generated CSV files and reports.
 */
function displayCsvDownloads(csvs, markdownReport = '', analysisSucceeded = true) {
    downloadContainer.innerHTML = '';

    // Add CSV download buttons
    csvs.forEach(csv => {
        const button = document.createElement('button');
        button.className = "inline-block bg-green-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 mr-2 mb-2";
        button.textContent = `Download ${csv.filename}`;
        button.addEventListener('click', () => {
            const blob = new Blob([csv.content], { type: 'text/csv;charset=utf-8;' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = csv.filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        });
        downloadContainer.appendChild(button);
    });

    // Add "Copy Report", "Download Report" (PDF), and "Download JSON" buttons if a markdown report is available
    if (markdownReport && analysisSucceeded) {
        // Button 1: Copy Report (Rendered)
        const copyButton = document.createElement('button');
        copyButton.className = "inline-block bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2 mb-2";
        copyButton.textContent = "Copy Report"; // Updated label to reflect rendered copy

        copyButton.addEventListener('click', () => {
            let reportElement = resultsContainer.querySelector('.prose');
            let targetDoc = document;

            // Handle case where report is inside an iframe
            if (!reportElement && resultsContainer.querySelector('iframe')) {
                const iframe = resultsContainer.querySelector('iframe');
                if (iframe.contentDocument) {
                    reportElement = iframe.contentDocument.body;
                    targetDoc = iframe.contentDocument;
                }
            }

            if (!reportElement) return;

            // Updated Copy Logic: Select the rendered content using Range API
            const selection = targetDoc.getSelection();
            const range = targetDoc.createRange();

            try {
                // clear any existing selection
                selection.removeAllRanges();

                // Select the entire contents of the report element
                range.selectNodeContents(reportElement);
                selection.addRange(range);

                // Execute copy command
                const successful = targetDoc.execCommand('copy');

                if (successful) {
                    const originalText = copyButton.textContent;
                    copyButton.textContent = "Copied!";
                    copyButton.classList.add('bg-green-500', 'hover:bg-green-600');
                    copyButton.classList.remove('bg-indigo-600', 'hover:bg-indigo-700');
                    setTimeout(() => {
                        copyButton.textContent = originalText;
                        copyButton.classList.remove('bg-green-500', 'hover:bg-green-600');
                        copyButton.classList.add('bg-indigo-600', 'hover:bg-indigo-700');
                    }, 2000);
                }
            } catch (err) {
                console.error('Failed to copy text.', err);
            } finally {
                // Always clear selection after attempting to copy
                if (selection) {
                    selection.removeAllRanges();
                }
            }
        });
        downloadContainer.appendChild(copyButton);

        // Button 2: Download Report (PDF)
        const downloadPdfButton = document.createElement('button');
        downloadPdfButton.className = "inline-block bg-blue-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 mr-2 mb-2";
        downloadPdfButton.textContent = "Download Report";
        downloadPdfButton.addEventListener('click', () => {
            let reportElement = resultsContainer.querySelector('.prose');
            if (!reportElement && resultsContainer.querySelector('iframe')) {
                reportElement = resultsContainer.querySelector('iframe').contentDocument.body;
            }
            const headerElement = document.getElementById('pageHeader');
            if (reportElement && typeof window.html2canvas !== 'undefined' && typeof window.jspdf !== 'undefined') {

                const originalFont = reportElement.style.fontFamily;
                reportElement.style.fontFamily = "'Helvetica', 'Arial', sans-serif";
                headerElement.style.display = 'none';

                requestAnimationFrame(() => {
                    setTimeout(() => {
                        html2canvas(reportElement, {
                            scale: 2,
                            useCORS: true,
                            windowWidth: reportElement.scrollWidth,
                            windowHeight: reportElement.scrollHeight
                        }).then(canvas => {
                            reportElement.style.fontFamily = originalFont;
                            headerElement.style.display = 'flex';

                            const { jsPDF } = window.jspdf;
                            const pdf = new jsPDF('p', 'mm', 'a4');
                            const pdfWidth = pdf.internal.pageSize.getWidth();
                            const pdfHeight = pdf.internal.pageSize.getHeight();
                            const topMargin = 25;
                            const bottomMargin = 25;
                            const leftMargin = 20;
                            const rightMargin = 20;
                            const usableWidth = pdfWidth - leftMargin - rightMargin;
                            const usableHeight = pdfHeight - topMargin - bottomMargin;

                            const imgData = canvas.toDataURL('image/png');
                            const canvasAspectRatio = canvas.height / canvas.width;
                            const totalImgHeight = usableWidth * canvasAspectRatio;

                            let heightLeft = totalImgHeight;
                            let position = 0;

                            const addHeaderFooter = (pdfInstance, pageNum, totalPages) => {
                                pdfInstance.setPage(pageNum);

                                // Add white rectangles to cover the margins and prevent content overlap
                                pdfInstance.setFillColor(255, 255, 255); // Set fill to white
                                pdfInstance.rect(0, 0, pdfWidth, topMargin, 'F'); // Header background
                                pdfInstance.rect(0, pdfHeight - bottomMargin, pdfWidth, bottomMargin, 'F'); // Footer background

                                pdfInstance.setFontSize(10);
                                pdfInstance.setTextColor(100);
                                pdfInstance.text('D.A.R.Y.L. Analysis Report', leftMargin, 15);
                                pdfInstance.text(`Generated: ${new Date().toLocaleDateString()}`, pdfWidth - rightMargin, 15, { align: 'right' });

                                const footerY = pdfHeight - 15;
                                pdfInstance.line(leftMargin, footerY - 5, pdfWidth - rightMargin, footerY - 5);
                                pdfInstance.text(`Page ${pageNum} of ${totalPages}`, pdfWidth / 2, footerY, { align: 'center' });
                            };

                            pdf.addImage(imgData, 'PNG', leftMargin, topMargin, usableWidth, totalImgHeight);
                            heightLeft -= usableHeight;

                            let page = 1;
                            while (heightLeft > 0) {
                                page++;
                                position -= usableHeight;
                                pdf.addPage();
                                pdf.addImage(imgData, 'PNG', leftMargin, position + topMargin, usableWidth, totalImgHeight);
                                heightLeft -= usableHeight;
                            }

                            const totalPages = pdf.internal.getNumberOfPages();
                            for (let i = 1; i <= totalPages; i++) {
                                addHeaderFooter(pdf, i, totalPages);
                            }

                            pdf.save('DARYL-Report.pdf');
                        }).catch(err => {
                            reportElement.style.fontFamily = originalFont;
                            headerElement.style.display = 'flex';
                            console.error("PDF generation failed:", err);
                        });
                    }, 100);
                });
            }
        });
        downloadContainer.appendChild(downloadPdfButton);
    }

    // Always add the JSON download button
    const jsonButton = document.createElement('button');
    jsonButton.className = "inline-block bg-teal-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 mb-2";
    jsonButton.textContent = "Download Retrieved Data (JSON)";
    if (typeof handleDownload !== 'undefined') {
        jsonButton.addEventListener('click', handleDownload);
    } else {
        console.warn('handleDownload function is not defined.');
    }
    downloadContainer.appendChild(jsonButton);


    downloadContainer.classList.remove('hidden');
}

/**
 * Creates and displays the search and download controls for per-ticket results.
 */
function displayPerTicketDownloadsAndSearch() {
    perTicketControlsContainer.innerHTML = `
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 items-center my-4">
            <div class="text-center">
                <button id="downloadPerTicketCsvBtn" class="bg-green-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-green-700">
                    Download Results (CSV)
                </button>
            </div>
            <div class="relative">
                <input type="text" id="perTicketSearchInput" placeholder="Search results..." class="w-full pl-4 pr-10 py-2 border border-slate-300 rounded-lg">
                <button id="clearPerTicketSearchBtn" class="absolute inset-y-0 right-0 flex items-center px-3 text-slate-500 hover:text-slate-700 hidden">
                    <svg xmlns="[http://www.w3.org/2000/svg](http://www.w3.org/2000/svg)" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                </button>
            </div>
        </div>
    `;
    perTicketControlsContainer.classList.remove('hidden');

    document.getElementById('downloadPerTicketCsvBtn').addEventListener('click', downloadPerTicketCsv);
    const searchInput = document.getElementById('perTicketSearchInput');
    const clearBtn = document.getElementById('clearPerTicketSearchBtn');
    searchInput.addEventListener('input', handlePerTicketSearch);
    clearBtn.addEventListener('click', () => {
        searchInput.value = '';
        handlePerTicketSearch({ target: searchInput });
    });
}

/**
 * Handles filtering the per-ticket result cards based on search input.
 */
function handlePerTicketSearch(event) {
    const query = event.target.value.toLowerCase().trim();
    const cards = resultsContainer.querySelectorAll('.status-card');
    document.getElementById('clearPerTicketSearchBtn').classList.toggle('hidden', !query);

    cards.forEach(card => {
        const cardText = card.innerText.toLowerCase();
        if (cardText.includes(query)) {
            card.style.display = '';
        } else {
            card.style.display = 'none';
        }
    });
}

/**
 * Generates and triggers a download for the per-ticket analysis results as a CSV file.
 */
function downloadPerTicketCsv() {
    const headers = ["Ticket ID", "Company Name", "Problem Summary", "Use-Case", "Product Module", "Ticket Type", "Ticket Status", "Severity"];
    const rows = allAnalysisResults.map(data => {
        if (data.error) return null;
        return [
            data.ticket_id,
            data.company_name || 'N/A',
            `"${(data.problem_summary || '').replace(/"/g, '""')}"`, // Handle quotes
            data.use_case,
            data.product_module,
            data.type,
            getStatusText(data.status),
            (getPriorityPill(data.priority).match(/>(.*?)</) || [])[1] // Extract text from pill
        ];
    }).filter(Boolean); // Remove null error rows

    const csvContent = "data:text/csv;charset=utf-8," +
        headers.join(",") + "\n" +
        rows.map(e => e.join(",")).join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "per_ticket_analysis_results.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}


/**
 * Displays an error message in the UI and provides fallback options.
 */
function displayError(message, isFatal = true) {
    if (message) {
        errorMessage.textContent = message;
        errorMessage.classList.remove('hidden');
        if (isFatal) {
            playNotificationSound('error');
            showOsNotification('Analysis Failed', message);
        }
    } else {
        errorMessage.classList.add('hidden');
    }
}


/**
 * Sets up the UI for manual processing after a fatal Gemini API failure.
 */
function displayManualFallbackUI(message, jobType) {
    displayError(message, true); // Display the core error
    resultsSection.classList.remove('hidden');
    loadingIndicator.classList.add('hidden');

    displayPromptForUser(false, jobType === 'overall');

    downloadContainer.innerHTML = '';
    const jsonButton = document.createElement('button');
    jsonButton.className = "inline-block bg-teal-600 text-white font-bold py-2 px-4 rounded-lg shadow-md hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 mb-2";
    jsonButton.textContent = "Download Retrieved Data (JSON)";
    jsonButton.addEventListener('click', handleDownload);
    downloadContainer.appendChild(jsonButton);
    downloadContainer.classList.remove('hidden');
    scrollToElement(resultsSection);
}



/**
 * Updates a progress bar's width and text content.
 */
function updateProgressBar(type, current, total) {
    const cappedCurrent = Math.min(current, total);
    const percent = total > 0 ? Math.round((cappedCurrent / total) * 100) : 0;
    const bar = type === 'fetch' ? fetchProgressBar : analysisProgressBar;
    const textEl = type === 'fetch' ? fetchProgressText : analysisProgressText;

    bar.style.width = `${percent}%`;
    bar.textContent = `${percent > 0 ? percent + '%' : ''}`;

    let timeString = '';
    if (analysisStartTime) {
        const elapsedTime = formatElapsedTime(Date.now() - analysisStartTime);
        timeString = ` (Elapsed: ${elapsedTime})`;
    }

    textEl.textContent = `Processed ${cappedCurrent} of ${total} tickets.${timeString}`;
}

/**
 * Displays the prompts in a textarea or returns the text.
 */
function displayPromptForUser(returnOnly = false, isOverall = false) {
    let promptText;
    let title;

    // Use the selected prompt if available, otherwise fall back to a generic message.
    if (isOverall && currentPrompt) {
        // For overall analysis, use the selected prompt
        promptText = currentPrompt.prompt;
        title = currentPrompt.name;
        // The prompt text might contain placeholders like [FILENAME_HERE], which we'll handle in the API call, not here.
    } else if (isOverall) {
        // Fallback for overall if no prompt is selected
        promptText = "No prompt was selected for overall analysis. Please select one from the Job Configuration section to use this feature.";
    } else {
        // Default message for per-ticket analysis
        promptText = "A specific prompt for per-ticket analysis is generated for each ticket individually. You can review the structure in the api.js file, function analyzeTicketWithGemini.";
    }

    if (returnOnly) {
        return promptText.trim();
    }

    const reportContainer = document.createElement('div');
    reportContainer.className = 'prose max-w-none p-4 bg-slate-100 rounded-lg border border-slate-200 text-sm';

    // Conditionally add a title for the prompt
    if (title) {
        const titleEl = document.createElement('h3');
        titleEl.className = "text-base font-semibold text-slate-800 mb-2";
        titleEl.textContent = `Prompt for Overall Analysis: ${title}`;
        reportContainer.appendChild(titleEl);
    }

    // Now handle the prompt content
    if (typeof marked !== 'undefined') {
        const renderer = new marked.Renderer();
        renderer.link = (href, title, text) => {
            const link = marked.Renderer.prototype.link.call(renderer, href, title, text);
            return link.replace(/^<a /, '<a target="_blank" rel="noopener noreferrer" ');
        };
        reportContainer.innerHTML += marked.parse(promptText.trim(), {
            mangle: false,
            headerIds: false,
            renderer: renderer
        });
    } else {
        const pre = document.createElement('pre');
        pre.className = 'whitespace-pre-wrap font-mono text-xs';
        pre.textContent = promptText.trim();
        reportContainer.appendChild(pre);
    }

    const copyButton = document.createElement('button');
    copyButton.title = 'Copy to clipboard';
    copyButton.className = 'absolute top-2.5 right-2.5 p-2 bg-slate-200 rounded-md hover:bg-slate-300 transition-colors opacity-0 group-hover:opacity-100';
    copyButton.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-slate-600"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>`;

    copyButton.addEventListener('click', () => {
        // Use document.execCommand('copy') for broader compatibility in iFrames
        const tempTextArea = document.createElement('textarea');
        tempTextArea.value = promptText.trim();
        document.body.appendChild(tempTextArea);
        tempTextArea.select();
        try {
            document.execCommand('copy');
            copyButton.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-green-600"><polyline points="20 6 9 17 4 12"></polyline></svg>`;
            setTimeout(() => {
                copyButton.innerHTML = `<svg xmlns="http://www.w3.org/2d000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-slate-600"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>`;
            }, 2000);
        } catch (err) {
            console.error('Failed to copy text.', err);
        } finally {
            document.body.removeChild(tempTextArea);
        }
    });

    promptContainer.innerHTML = '';
    promptContainer.appendChild(reportContainer);
    promptContainer.appendChild(copyButton);
    promptContainer.classList.remove('hidden');
}


// --- Logo Animation Functions ---

function showProcessingAnimation() {
    isProcessing = true;
    logoImage.classList.add('hidden');
    logoVideo.classList.remove('hidden');
    logoVideo.play();
}

function hideProcessingAnimation() {
    isProcessing = false;
    logoImage.classList.remove('hidden');
    logoVideo.classList.add('hidden');
    logoVideo.currentTime = 0;
}

// --- UI Helper Functions ---

function scrollToElement(element, offset = 20) {
    if (!element) return;
    const elementPosition = element.getBoundingClientRect().top;
    const offsetPosition = elementPosition + window.pageYOffset - offset;
    window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth'
    });
}

function updateSettingsBadge() {
    let missingCount = 0;
    const isDummy = dummyModeCheckbox.checked;
    const isUploadExtract = extractionProfileSelect.value === 'upload-extract';

    if (!fsDomainInput.value.trim() && !isUploadExtract) missingCount++;
    if (!fsApiKeyInput.value.trim() && !isUploadExtract) missingCount++;

    if (!isDummy) {
        if (!geminiApiKeyInput.value.trim()) missingCount++;
        if (!geminiModelSelect.value.trim()) missingCount++;

        const jobType = document.querySelector('input[name="jobType"]:checked').value;
        if (jobType === 'perTicket') {
            if (!productModulesInput.value.trim()) missingCount++;
            if (!useCasesInput.value.trim()) missingCount++;
        }
    }

    if (missingCount > 0) {
        settingsBadge.textContent = missingCount;
        settingsBadge.classList.remove('hidden');
        configOverlay.classList.remove('hidden');
        fileUploadInput.disabled = true;
    } else {
        settingsBadge.classList.add('hidden');
        configOverlay.classList.add('hidden');
        fileUploadInput.disabled = false;
    }
}

function toggleRequiredIndicators() {
    const isDummy = dummyModeCheckbox.checked;
    const isUploadExtract = extractionProfileSelect.value === 'upload-extract';

    // Hide FS keys if Upload Extract is active
    if (fsDomainRequiredStar) fsDomainRequiredStar.classList.toggle('hidden', isUploadExtract);
    if (fsApiKeyRequiredStar) fsApiKeyRequiredStar.classList.toggle('hidden', isUploadExtract);

    if (geminiRequiredStar) geminiRequiredStar.classList.toggle('hidden', isDummy);
    if (geminiModelRequiredStar) geminiModelRequiredStar.classList.toggle('hidden', isDummy);
    if (modulesRequiredStar) modulesRequiredStar.classList.toggle('hidden', isDummy);
    if (useCasesRequiredStar) useCasesRequiredStar.classList.toggle('hidden', isDummy);
}

/**
 * Displays the final analysis statistics.
 */
function displayAnalysisStats() {
    const totalTime = analysisEndTime - analysisStartTime;
    e2eTimeDisplay.textContent = formatElapsedTime(totalTime);

    const atr = parseInt(atrInput.value, 10);
    const ticketsAnalyzed = allFetchedData.filter(t => !t.error).length;

    // Standard calculation for ticket review time saved
    let baseTimeSaved = ticketsAnalyzed * atr;

    // Add 30% overhead for manual report building/consolidation
    let totalTimeSaved = baseTimeSaved * 1.30;

    // Add time for any "Deeper Analysis" clicks, which represents a full manual review saved
    if (extendedAnalysesCount > 0) {
        const extendedTimeSaved = extendedAnalysesCount * atr * 1.30; // Also add overhead here
        totalTimeSaved += extendedTimeSaved;
    }

    timeSavedDisplay.textContent = formatTimeSaved(totalTimeSaved);


    const model = geminiModelSelect.value;
    apiCostDisplay.textContent = calculateGeminiCost(model, totalInputTokens, totalOutputTokens);

    statsSection.classList.remove('hidden');
}


function displayTokenCountWarning(tokenCount, tokenLimit, filename) {
    if (!tokenCountWarning) return;

    tokenCountWarning.innerHTML = `
        <h4 class="font-bold">Token Limit Warning</h4>
        <p class="mt-1 text-sm">The total token count for your analysis is estimated to be ${tokenCount} tokens, which exceeds the model's limit of ${tokenLimit} tokens.</p>
        <p class="mt-2 text-sm">This analysis will likely fail. Please select a larger model (e.g., Gemini 1.5 Pro) or reduce the number of tickets.</p>
        <p class="mt-2 text-sm font-semibold">The raw data has been uploaded to the Gemini File API with the name <code class="bg-yellow-200 p-0.5 rounded">${filename}</code> and can be used for a new analysis with a different model without re-fetching from FreshService.</p>
    `;
    tokenCountWarning.classList.remove('hidden');
}


// --- Modal Functions ---

/**
 * Opens the Prompts modal and prepares it for viewing.
 */
function openPromptsModal() {
    promptsModal.classList.remove('hidden');
    initializePrompts();
    const modalContent = promptsModal.querySelector('.modal-scroll-content');
    if (modalContent) {
        modalContent.scrollTop = 0;
    }
}


async function openFieldLoader(targetId) {
    currentTargetTextarea = document.getElementById(targetId);
    fieldLoaderModal.classList.remove('hidden');
    modalContent.classList.add('hidden');
    modalError.classList.add('hidden');
    modalSpinner.classList.remove('hidden');

    const domain = fsDomainInput.value.trim();
    const apiKey = fsApiKeyInput.value.trim();

    if (!domain || !apiKey) {
        modalError.textContent = 'Please enter your FreshService Domain and API Key before loading options.';
        modalError.classList.remove('hidden');
        modalSpinner.classList.add('hidden');
        return;
    }

    if (!sanitizeApiKey(apiKey)) {
        modalError.textContent = 'The FreshService API Key appears to contain invalid characters (like spaces). Please check your key.';
        modalError.classList.remove('hidden');
        modalSpinner.classList.add('hidden');
        return;
    }

    try {
        const fields = await fetchTicketFields();
        const selectableFields = fields.filter(field => field.choices && field.choices.length > 0);
        fieldSelect.innerHTML = '<option value="">-- Select a Field --</option>';
        selectableFields.forEach(field => {
            const option = document.createElement('option');
            option.value = field.id;
            option.textContent = field.label;
            fieldSelect.appendChild(option);
        });
        fieldChoicesPreview.textContent = 'Select a field to see its options.';
        modalUseBtn.disabled = true;
        modalContent.classList.remove('hidden');
    } catch (error) {
        modalError.textContent = `Error: ${error.message}. Check domain/API key and API response structure.`;
        modalError.classList.remove('hidden');
    } finally {
        modalSpinner.classList.add('hidden');
    }
}

function closeFieldLoader() {
    fieldLoaderModal.classList.add('hidden');
    currentTargetTextarea = null;
}

function updateFieldChoicesPreview() {
    const selectedFieldId = fieldSelect.value;
    if (!selectedFieldId) {
        fieldChoicesPreview.textContent = 'Select a field to see its options.';
        modalUseBtn.disabled = true;
        return;
    }
    const selectedField = ticketFieldsCache.find(f => f.id == selectedFieldId);
    if (selectedField) {
        fieldChoicesPreview.innerHTML = selectedField.choices.map(choice => `<div>${choice.value}</div>`).join('');
        modalUseBtn.disabled = false;
    }
}

function useSelectedFieldOptions() {
    const selectedFieldId = fieldSelect.value;
    const selectedField = ticketFieldsCache.find(f => f.id == selectedFieldId);
    if (currentTargetTextarea && selectedField) {
        const optionsText = selectedField.choices.map(choice => choice.value).join('\n');
        currentTargetTextarea.value = optionsText;
    }
    closeFieldLoader();
}

function updateModelDropdown() {
    const originalSelection = localStorage.getItem('geminiModel');
    const modelsToShow = availableGeminiModels;

    geminiModelSelect.innerHTML = '';

    if (modelsToShow.length === 0) {
        geminiModelSelect.innerHTML = `<option value="">No compatible models found</option>`;
        return;
    }

    modelsToShow.forEach(model => {
        const option = document.createElement('option');
        const modelId = model.name.split('/')[1];
        option.value = modelId;
        option.textContent = model.displayName;
        geminiModelSelect.appendChild(option);
    });

    if (originalSelection && modelsToShow.some(m => m.name.split('/')[1] === originalSelection)) {
        geminiModelSelect.value = originalSelection;
    } else if (modelsToShow.length > 0) {
        geminiModelSelect.selectedIndex = 0;
    }

    saveSettings();
    updateSettingsBadge();
}

/**
 * Displays the selected prompt's description.
 * @param {object} prompt - The prompt object to display.
 */
function displaySelectedPromptDescription(prompt) {
    if (prompt && prompt.description) {
        promptDescriptionText.textContent = prompt.description;
        promptDescriptionContainer.classList.remove('hidden');
        clearPromptSelectionBtn.classList.remove('hidden'); // Show clear button
    } else {
        handleClearPromptSelection(false);
    }
}

/**
 * Shows the extended details modal and triggers the secondary analysis.
 * @param {object} analyzedData The combined analysis and ticket data.
 * @param {object} rawFetchedData The raw ticket data object.
 * @param {string} fsDomain The FreshService domain for link construction.
 */
async function showExtendedDetailsModal(analyzedData, rawFetchedData, fsDomain) {
    if (!rawFetchedData) {
        console.error("Cannot show extended details: raw fetched data is missing.", analyzedData);
        alert("An error occurred: Could not find the complete data for this ticket to perform a detailed analysis.");
        return;
    }

    const isFsFetch = extractionProfileSelect.value !== 'upload-extract';

    // Construct title link only if we are fetching from FS
    const domain = fsDomain.trim().replace(/^https?:\/\//, '');
    const titleHtml = (domain && isFsFetch) ?
        `<a href="https://${domain}/a/tickets/${analyzedData.ticket_id}" target="_blank" class="text-indigo-600 hover:underline">Ticket #${analyzedData.ticket_id}</a>` :
        `Ticket #${analyzedData.ticket_id}`;

    extendedTicketModalTitle.innerHTML = `Details for ${titleHtml}`;

    extendedTicketModalContent.innerHTML = `
        <div class="space-y-3">
            <div class="grid grid-cols-[max-content,1fr] gap-y-2 text-sm">
                <!-- ... content from analyzedData ... -->
                <div class="font-semibold text-slate-600 text-right pr-2.5">Company Name:</div><div class="text-slate-900 pl-2.5">${analyzedData.company_name || 'N/A'}</div>
                <div class="font-semibold text-slate-600 text-right pr-2.5">Problem Summary:</div><div class="text-slate-900 pl-2.5">${analyzedData.problem_summary || 'N/A'}</div>
                <div class="font-semibold text-slate-600 text-right pr-2.5">Use-Case:</div><div class="text-slate-900 pl-2.5">${analyzedData.use_case || 'N/A'}</div>
                <div class="font-semibold text-slate-600 text-right pr-2.5">Product Module:</div><div class="text-slate-900 pl-2.5">${analyzedData.product_module || 'N/A'}</div>
                <div class="font-semibold text-slate-600 text-right pr-2.5">Ticket Type:</div><div class="text-slate-900 pl-2.5">${analyzedData.type || 'N/A'}</div>
                <div class="font-semibold text-slate-600 text-right pr-2.5">Ticket Status:</div><div class="text-slate-900 pl-2.5">${getStatusText(analyzedData.status)}</div>
            </div>
            <hr>
            <div id="extendedAnalysisContent">
                <!-- Spinner or cached content will go here -->
            </div>
            <div class="border-t pt-4 flex justify-end">
                 <button id="modalCloseFooterBtn" class="bg-slate-200 text-slate-800 font-bold py-2 px-4 rounded-lg hover:bg-slate-300">Close</button>
            </div>
        </div>
    `;

    document.getElementById('modalCloseFooterBtn').addEventListener('click', () => extendedTicketModal.classList.add('hidden'));
    extendedTicketModal.classList.remove('hidden');
    const extendedContent = document.getElementById('extendedAnalysisContent');

    // Check cache first
    if (extendedAnalysisCache[analyzedData.ticket_id]) {
        const cachedResult = extendedAnalysisCache[analyzedData.ticket_id];
        extendedContent.innerHTML = `
            <div class="space-y-3">
                <div><h4 class="font-semibold text-slate-800 text-base mb-1">Root Cause Analysis</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(cachedResult.root_cause)}</div></div>
                <div><h4 class="font-semibold text-slate-800 text-base mb-1">Suggested Next Steps</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(cachedResult.next_steps)}</div></div>
                <div><h4 class="font-semibold text-slate-800 text-base mb-1">Preventative Measures</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(cachedResult.preventative_measures)}</div></div>
            </div>`;
        return;
    }

    // Check for dummy mode
    if (dummyModeCheckbox.checked) {
        extendedContent.innerHTML = `<div class="text-yellow-600 bg-yellow-100 p-3 rounded-md"><h4 class="font-bold">Deeper Analysis Skipped (Dummy Mode)</h4><p>Deeper analysis is not available in Dummy Mode.</p></div>`;
        return;
    }

    // Check for API Key
    const geminiKey = geminiApiKeyInput.value.trim();
    const selectedModel = geminiModelSelect.value;
    if (!geminiKey || !selectedModel) {
        extendedContent.innerHTML = `<div class="text-red-600 bg-red-100 p-3 rounded-md"><h4 class="font-bold">Deeper Analysis Blocked</h4><p>Please configure the Gemini API Key and Model in Settings to run Deeper Analysis.</p></div>`;
        return;
    }


    // If not cached, show spinner and fetch
    extendedContent.innerHTML = `<div class="flex items-center justify-center p-4"><div class="dot-flashing"></div><span class="ml-4 text-slate-600">Performing deeper analysis...</span></div>`;

    try {
        const { result: extendedResult, usage } = await analyzeTicketForExtendedDetails(rawFetchedData, geminiKey, selectedModel);

        // Cache the result
        extendedAnalysisCache[analyzedData.ticket_id] = extendedResult;

        // Update stats
        totalInputTokens += usage.input;
        totalOutputTokens += usage.output;
        extendedAnalysesCount++;
        displayAnalysisStats();


        // Update the card in the main view to show the new pill
        const cardToUpdate = resultsContainer.querySelector(`.status-card[data-ticket-id="${analyzedData.ticket_id}"]`);
        if (cardToUpdate) {
            // Need to pass the domain here as well
            cardToUpdate.innerHTML = generateCardHTML(analyzedData, fsDomain);
        }

        if (extendedContent) { // Check if modal is still open
            extendedContent.innerHTML = `
                <div class="space-y-3">
                    <div><h4 class="font-semibold text-slate-800 text-base mb-1">Root Cause Analysis</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(extendedResult.root_cause)}</div></div>
                    <div><h4 class="font-semibold text-slate-800 text-base mb-1">Suggested Next Steps</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(extendedResult.next_steps)}</div></div>
                    <div><h4 class="font-semibold text-slate-800 text-base mb-1">Preventative Measures</h4><div class="text-sm text-slate-700 prose max-w-none">${marked.parse(extendedResult.preventative_measures)}</div></div>
                </div>`;
        }
    } catch (error) {
        console.error("Extended analysis failed:", error);
        if (extendedContent) { // Check if modal is still open
            extendedContent.innerHTML = `<div class="text-red-600 bg-red-100 p-3 rounded-md"><h4 class="font-bold">Deeper Analysis Failed</h4><p>${error.message}</p></div>`;
        }
    }
}